dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master

before_script:
  - env | sort
  - name="roundcubemail"
  - image="roundcube/roundcubemail:${VERSION}${VARIANT:+-$VARIANT}"
  - dir="${VERSION}/${VARIANT}"

script:
  - travis_retry docker build -t "$image" "$dir"

after_script:
  - docker images
  - docker run --name "$name" -d "$image" "$dir"
  - docker ps
  - docker logs "$name"

notifications:
  email: false

env:
  - VERSION=1.4-rc1 VARIANT=apache
  - VERSION=1.4-rc1 VARIANT=fpm
  - VERSION=1.4-rc1 VARIANT=fpm-alpine
  - VERSION=1.3.8 VARIANT=apache
  - VERSION=1.3.8 VARIANT=fpm
  - VERSION=1.3.8 VARIANT=fpm-alpine
