dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master
    - develop

before_script:
  - env | sort
  - dir="images/${VERSION}/${VARIANT}"

script:
  - cd "$dir"
  - docker-compose build
  - docker images
  - travis_retry docker-compose up -d && sleep 60
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps "roundcubedb" | grep "Up"
  - docker-compose ps "roundcube" | grep "Up"

notifications:
  email: false

env:
  - VERSION=1.4-rc1 VARIANT=apache
  - VERSION=1.4-rc1 VARIANT=fpm
  - VERSION=1.4-rc1 VARIANT=fpm-alpine
  - VERSION=1.3 VARIANT=apache
  - VERSION=1.3 VARIANT=fpm
  - VERSION=1.3 VARIANT=fpm-alpine
